/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JogoDaVelha;

import static JogoDaVelha.StatusCelula.BOLA;
import static JogoDaVelha.StatusCelula.XIS;

/**
 *
 * @author taohs
 */
public class GUIjava extends javax.swing.JFrame {
    Jogadores player1;
    Jogadores player2;
    Historico historico;
            
            
    int op;
    
    
    private LogicaJogo game;
    /**
     * Creates new form GUIjava
     */
    public GUIjava() {
        player1 = new Jogador1("X");
        player2 = new Jogador2("O");
        historico = new Historico();
        game = new LogicaJogo();
        game.iniciar();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        txtvisor = new javax.swing.JTextField();
        jButao00 = new javax.swing.JButton();
        jButao02 = new javax.swing.JButton();
        jButao01 = new javax.swing.JButton();
        jButao10 = new javax.swing.JButton();
        jButao11 = new javax.swing.JButton();
        jButao12 = new javax.swing.JButton();
        jButao20 = new javax.swing.JButton();
        jButao21 = new javax.swing.JButton();
        jButao22 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Jogo desenvolvido por:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tao Hansen");

        jLabel3.setText("Jogo da Velha - versão 0.0.1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Velha");
        setResizable(false);

        txtvisor.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        txtvisor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvisorActionPerformed(evt);
            }
        });

        jButao00.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao00ActionPerformed(evt);
            }
        });

        jButao02.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao02ActionPerformed(evt);
            }
        });

        jButao01.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao01ActionPerformed(evt);
            }
        });

        jButao10.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao10ActionPerformed(evt);
            }
        });

        jButao11.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao11ActionPerformed(evt);
            }
        });

        jButao12.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao12ActionPerformed(evt);
            }
        });

        jButao20.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao20ActionPerformed(evt);
            }
        });

        jButao21.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao21ActionPerformed(evt);
            }
        });

        jButao22.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButao22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButao22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButao22ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        jMenuItem1.setText("Novo Jogo");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sobre");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtvisor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButao00, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButao01, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButao02, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButao10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButao11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButao12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButao20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButao21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButao22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButao00, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButao02, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButao01, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButao10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButao12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButao11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButao20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButao22, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButao21, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButao00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao00ActionPerformed
        verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(0, 0, XIS);
            jButao00.setText(game.getValorCelula(0, 0).toString());
            historico.addHistorico(player1.getNome(), "[0,0]");
        } else {
            game.setCelulaNoTabuleiro(0, 0, BOLA);
            jButao00.setText(game.getValorCelula(0, 0).toString());
            historico.addHistorico(player2.getNome(), "[0,0]");
        }
        jButao00.setEnabled(false);
        
        verVencedor();        
    }//GEN-LAST:event_jButao00ActionPerformed

    private void jButao02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao02ActionPerformed
           verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(0, 2, XIS);
            jButao02.setText(game.getValorCelula(0, 2).toString());
            historico.addHistorico(player1.getNome(), "[0,2]");
        } else {
            game.setCelulaNoTabuleiro(0, 2, BOLA);
            jButao02.setText(game.getValorCelula(0, 2).toString());
            historico.addHistorico(player2.getNome(), "[0,2]");
        }
        jButao02.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao02ActionPerformed

    private void jButao01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao01ActionPerformed
           verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(0, 1, XIS);
            historico.addHistorico(player1.getNome(), "[0,1]");
            jButao01.setText(game.getValorCelula(0, 1).toString());
        } else {
            game.setCelulaNoTabuleiro(0, 1, BOLA);
            historico.addHistorico(player2.getNome(), "[0,1]");
            jButao01.setText(game.getValorCelula(0, 1).toString());
        }
        jButao01.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao01ActionPerformed

    private void jButao10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao10ActionPerformed
        verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(1, 0, XIS);
            historico.addHistorico(player1.getNome(), "[1,0]");
            jButao10.setText(game.getValorCelula(1, 0).toString());
        } else {
            game.setCelulaNoTabuleiro(1, 0, BOLA);
            historico.addHistorico(player2.getNome(), "[1,0]");
            jButao10.setText(game.getValorCelula(1, 0).toString());
        }
        jButao10.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao10ActionPerformed

    private void jButao11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao11ActionPerformed
               verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(1, 1, XIS);
            historico.addHistorico(player1.getNome(), "[1,1]");
            jButao11.setText(game.getValorCelula(1, 1).toString());
        } else {
            game.setCelulaNoTabuleiro(1, 1, BOLA);
            historico.addHistorico(player2.getNome(), "[1,1]");
            jButao11.setText(game.getValorCelula(1, 1).toString());
        }
        jButao11.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao11ActionPerformed

    private void jButao12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao12ActionPerformed
                verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(1, 2, XIS);
            historico.addHistorico(player1.getNome(), "[1,2]");
            jButao12.setText(game.getValorCelula(1, 2).toString());
        } else {
            game.setCelulaNoTabuleiro(1, 2, BOLA);
            historico.addHistorico(player2.getNome(), "[1,2]");
            jButao12.setText(game.getValorCelula(1, 2).toString());
        }
        jButao12.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao12ActionPerformed

    private void jButao20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao20ActionPerformed
               verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(2, 0, XIS);
            historico.addHistorico(player1.getNome(), "[2,0]");
            jButao20.setText(game.getValorCelula(2, 0).toString());
        } else {
            game.setCelulaNoTabuleiro(2, 0, BOLA);
            historico.addHistorico(player2.getNome(), "[2,0]");
            jButao20.setText(game.getValorCelula(2, 0).toString());
        }
        jButao20.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao20ActionPerformed

    private void jButao21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao21ActionPerformed
               verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(2, 1, XIS);
            historico.addHistorico(player1.getNome(), "[2,1]");
            jButao21.setText(game.getValorCelula(2, 1).toString());
        } else {
            game.setCelulaNoTabuleiro(2, 1, BOLA);
            historico.addHistorico(player2.getNome(), "[2,1]");
            jButao21.setText(game.getValorCelula(2, 1).toString());
        }
        jButao21.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao21ActionPerformed

    private void jButao22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButao22ActionPerformed
                verificaJogadordaVez();
        if (op == 1) {
            game.setCelulaNoTabuleiro(2, 2, XIS);
            historico.addHistorico(player1.getNome(), "[2,2]");
            jButao22.setText(game.getValorCelula(2, 2).toString());
        } else {
            game.setCelulaNoTabuleiro(2, 2, BOLA);
            historico.addHistorico(player2.getNome(), "[2,2]");
            jButao22.setText(game.getValorCelula(2, 2).toString());
        }
        jButao22.setEnabled(false);
        verVencedor();
    }//GEN-LAST:event_jButao22ActionPerformed

    private void verVencedor(){
        String Vencedor = game.verificaVencedor();
        if (Vencedor != ""){
            if (Vencedor == player1.getMarca()){
                DesativaB();
            txtvisor.setText("O Vencedor foi "+player1.getNome());}
            
            else if (Vencedor == player2.getMarca()){
                    DesativaB();
                    txtvisor.setText("O Vencedor foi "+player2.getNome());
                    historico.exibeHistorico();
            }
            
                   }
        }
    
    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtvisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvisorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
   
    public void DesativaB(){
        jButao00.setEnabled(false);
        jButao01.setEnabled(false);
        jButao02.setEnabled(false);
        jButao10.setEnabled(false);
        jButao11.setEnabled(false);
        jButao12.setEnabled(false);
        jButao20.setEnabled(false);
        jButao21.setEnabled(false);
        jButao22.setEnabled(false);
    }
    
    public void restartBotoes(){
       jButao00.setText("");
       jButao00.setEnabled(true);
       jButao01.setText("");
       jButao01.setEnabled(true);
       jButao02.setText("");
       jButao02.setEnabled(true);
       jButao10.setText("");
       jButao10.setEnabled(true);
       jButao11.setText("");
       jButao11.setEnabled(true);
       jButao12.setText("");
       jButao12.setEnabled(true);
       jButao20.setText("");
       jButao20.setEnabled(true);
       jButao21.setText("");
       jButao21.setEnabled(true);
       jButao22.setText("");
       jButao22.setEnabled(true);
       txtvisor.setText("");
       game.reset();
    } 
    
    
    public void verificaJogadordaVez(){
        if(player1.isPlayer()&&player2.isPlayer()){
            this.op=1;
            player1.setPlayer(false);
            player2.setPlayer(true);
            txtvisor.setText("Sua vez  "+player2.getNome());
        }else if(player1.isPlayer()&&(player2.isPlayer()==false)){
            this.op=1;
            player1.setPlayer(false);
            player2.setPlayer(true);
            txtvisor.setText("Sua vez "+player2.getNome());
        }else {
            this.op=2;
            player1.setPlayer(true);
            player2.setPlayer(false);
            txtvisor.setText("Sua vez "+player1.getNome());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIjava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogicaJogo game = new LogicaJogo();
                game.iniciar();
                new GUIjava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButao00;
    private javax.swing.JButton jButao01;
    private javax.swing.JButton jButao02;
    private javax.swing.JButton jButao10;
    private javax.swing.JButton jButao11;
    private javax.swing.JButton jButao12;
    private javax.swing.JButton jButao20;
    private javax.swing.JButton jButao21;
    private javax.swing.JButton jButao22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtvisor;
    // End of variables declaration//GEN-END:variables
}
